upstreams:
    init:
        strategy: blocking
    groups:
      default:
        - 127.0.0.1:5335
    strategy: strict
    timeout: 2s

connectIPVersion: v4

blocking:
    denylists:
        ads:
            - /app/denylists/blocklist.txt
            - https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn/hosts
            - https://v.firebog.net/hosts/lists.php?type=tick
            - https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/doh-vpn-proxy-bypass.txt
            - https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/nosafesearch.txt
    allowlists:
        ads:
            - /app/allowlists/allowlist.txt
            - https://raw.githubusercontent.com/anudeepND/whitelist/refs/heads/master/domains/whitelist.txt
    clientGroupsBlock:
        default:
            - ads
    blockType: nxDomain
    blockTTL: 1h
    loading:
        refreshPeriod: 24h
        downloads:
          timeout: 60s
          writeTimeout: 60s
          readTimeout: 60s
          readHeaderTimeout: 60s
          attempts: 3
          cooldown: 500ms
          cachePath: /app/cache
        concurrency: 4
        strategy: blocking
        maxErrorsPerSource: 5

customDNS:
    customTTL: 1h
    zone: |
        $ORIGIN google.com.
        @   3600 CNAME forcesafesearch.google.com.
        www 3600 CNAME forcesafesearch.google.com.
        $ORIGIN bing.com.
        www 3600 CNAME strict.bing.com.
        $ORIGIN duckduckgo.com.
        @   3600 CNAME safe.duckduckgo.com.
        $ORIGIN youtube.com.
        www 3600 CNAME restrictmoderate.youtube.com.
        m   3600 CNAME restrictmoderate.youtube.com.
        $ORIGIN googleapis.com.
        youtubei 3600 CNAME restrictmoderate.youtube.com.

caching:
    minTime: 5m
    maxTime: 0m
    maxItemsCount: 0
    prefetching: true

rebindingProtection:
    enable: true

rateLimit:
    enable: true
    rate: 100
    burst: 200

ports:
    dns: 53

ede:
    enable: true

dnssec:
    validate: false
