FROM debian:stable-slim

ENV LANG en_US.utf8

RUN apt-get update && apt-get install -y --no-install-recommends \
    locales \
    unbound \
    unbound-anchor \
    unbound-host \
    dns-root-data \
    && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8 \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /var/lib/unbound && cp /usr/share/dns/root.key /var/lib/unbound/root.key

COPY unbound.conf /etc/unbound/unbound.conf

RUN chown -R unbound:unbound /etc/unbound /var/lib/unbound

EXPOSE 5335/udp 5335/tcp

CMD ["unbound"]
